version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    pull-request-branch-name:
      separator: "-"
  - package-ecosystem: docker
    directory: "/Dockerfile.*"
    schedule:
      interval: daily
    pull-request-branch-name:
      separator: "-"
