name: Release

on:
  push:
    #    branches:
    #      - 'main'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image: ['alpine', 'debian', 'ubuntu']

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker buildx bake ${{ matrix.image }}

      - name: Install bats
        run: npm install -g bats@1.10.0

      - name: Test Docker image
        run: bats test/${{ matrix.image }}.bats
